services:
  libretranslate:
    image: libretranslate/libretranslate
    environment:
      - LT_LOAD_ONLY=en,fr,es,it,de
    ports:
      - "5000:5000"
    restart: unless-stopped
    stdin_open: true
    tty: true

  server:
    build: .
    depends_on:
      - libretranslate
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true